# Generated by Django 4.2.7 on 2023-11-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Phone_number',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('신용카드', 'Credit Card'), ('무통장 입금', 'Bank Transfer')], default='CC', max_length=10),
        ),
    ]
