# Generated by Django 4.2.7 on 2023-11-23 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_order_phone_number_alter_order_payment_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Phone_number',
            new_name='phone_number',
        ),
    ]
