# Generated by Django 4.2.7 on 2023-11-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_rename_phone_number_order_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('신용카드', '신용카드'), ('무통장 입금', '무통장 입금')], default='CC', max_length=10),
        ),
    ]
